[package]
name = "yomi_dict_db"
version = "0.0.0"
edition = "2021"

[lib]
name = "yomi_dict_db"
path = "src/yomi_dict_db.rs"

[dependencies]
rusqlite = { version = "0.33.0", features = ["bundled"] }
zip = "2.2.2"
